name: runcycle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  health: ^13.1.1
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.3.0
  device_info_plus: ^11.5.0
  intl: ^0.20.2
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  flutter_timezone: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true